filter:
    excluded_paths: [tests/*]
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 3
build:
    deployment:
        -
            branch: master          # you can use either the full branch name,
            branch: feature_*       # an asterisc for e.g. any feature branches
            branch: /feature_.*/    # or the same as a regular expression
            commands:
                - cd deploy && fab deploy 
