filter:
    excluded_paths:
        - tests/*

build:
    environment:
        php:
            version: 7.0.7
build:
    deployment:
        -
            branch: master          # you can use either the full branch name,
            branch: feature_*       # an asterisc for e.g. any feature branches
            branch: /feature_.*/    # or the same as a regular expression
            commands:
                - cd deploy && cap deploy 
checks:
    php:
        code_rating: true
        duplication: true

    python:
        code_rating: true
        duplicate_code: true

    ruby:
        code_rating: true
        duplicate_code: true
